id: P3C93E5C0
initial_creation_type: input
source_metadata:
  title: Kaivalyopaniṣad
  language:
  - English
  - Sanskrit
  term: Sanskrit -- Veda -- Upaniṣad
  data entry: Jost Gippert
  contribution to GRETIL: Jost Gippert
  initial normalization and conversion to legacy GRETIL formats: Reinhold Grünendahl
  normalization and conversion to TEI-conformant markup: Maximilian Mehner
created_at: '2022-03-09T14:48:14.691601'
last_modified_at: '2022-03-09T14:48:14.691613'
